### ISSUE TITLE
About SMPL(mosh) label .

### ISSUE THREAD

**Issue by www516717402** [CalciferZh/minimal-hand#30]
Hello, Ask a question again.
There is no mosh(SMPL _theta_ and _beta_) in STB、RHD、FreiHand dataset etc. How to translate 3D keypoints to mesh(SMPL _theta_ _beta_)?
Hope your reply, thanks.

**Comment by CalciferZh** [comment]
[This](https://github.com/CalciferZh/Minimal-IK) might be helpful.
In the paper we did not use such data for supervision on theta.

**Comment by www516717402** [comment]
Great! Just solved my problem. Thank you much.

**Comment by www516717402** [comment]
In paper sec3.2 include Shape(beta) Estimation. There is only theta in project.

**Comment by CalciferZh** [comment]
Yes we did not include the shape estimation part into this repo. Shape estimation is an optional module and easy to implement, so we did not put it here.

**Comment by www516717402** [comment]
Thank you.

**Comment by pablovela5620** [comment]
Regarding the supervision from the MANO scans, my understanding is that you input root-relative normalized XYZ coordinates you get an output 20x4 quaternion rotations. Are you being given the quaternion rotations (or axis-angle) from the MANO hand scan registrations? or do you calculate them using that simple-ik implementation you shared above? Would this also not work for something like the FrieHAND dataset since they also include the shape/pose annotations, giving significantly more varied hand poses and views?

**Comment by CalciferZh** [comment]
Yes the joint rotations are in the MANO data already.
The method works for any dataset that provides paired XYZ coordinates and joint angles, including FreiHand.
However, we specifically note that the "GT" rotations in the FreiHand dataset actually comes from an optimization based IK approach, which is less reliable than the registration approach used in MANO. If you check into the data, you'll find a few poses in FreiHand that are not completely correct, e.g. sample ID 32342/9359/12456. Our IKNet, trained with MANO scans, sometimes can even give better results than the FreiHand GT.

**Comment by pablovela5620** [comment]
Gotcha, thanks for the info! I do wonder though since the amount of good data available through the MANO scans is dwarfed by the size of something like FreiHand (even though I remember reading that your team did some sort of data augmentation to get more samples along with the weakly supervised 3d pos data). Would you say that its the combination of the weakly supervised data + mano is what allows it to outperform? I would definitely love to see some comparisons

**Comment by CalciferZh** [comment]
My personal feeling, without proof, is that the size of data is not that important, as the valid pose space is not quite large, especially for hands. It doesn't need millions of samples to cover all possible hand poses, which is very different from image-based tasks.
We are not claiming that we outperform FreiHand, but we did found a few samples where we have visually better results, as follows. (Left FreiHand, right ours)
![image](https://user-images.githubusercontent.com/20183700/86199301-51c67e80-bb8c-11ea-99d8-733edacff147.png)
Also I need to note that the IKNet used in the above image is not exactly the one we released here, but with some improvements after the publication. The general idea is the same, though. I can't talk about it in more detail, as I'm not working direclty on that project now.

**Comment by pablovela5620** [comment]
Totally understand! for the comparison above, is the FreiHand example of a model directly predicting the shape and pose parameters and the IKNet directly regressing the quaternions (which are then posed)? or is the left example also IKNet but instead of using the MANO registrations as supervision the FreiHand dataset was used? 

Just for a bit more clarity on my side. The reason I ask about FreiHand is as a potential source to train your IKNet. One of the major benefits that come from this approach (as I'm sure you know) is the incredible speed over trying to use iterative optimization-based IK. But I have been having some trouble with it when it comes to hand poses where the hand is more horizontal. I am using a different 3d predictor (the one from googles mediapipe which seems to be very accurate) and it seems to make IKNet produce really good results compared to using the shipped DetNet EXCEPT for horizontal poses. I wanted to see if potentially retraining IKNet with this new 3d detector + the supervision from the Freihand dataset would help performance.

**Comment by CalciferZh** [comment]
The left example is the GT pose provided in the FreiHand dataset.
I agree with you that retraining the IKNet would be helpful. Personally I would use MANO for rotational supervision, and FreiHand for weak supervision (maybe plus other datasets).

**Comment by MengHao666** [comment]
> Regarding the supervision from the MANO scans, my understanding is that you input root-relative normalized XYZ coordinates you get an output 20x4 quaternion rotations. Are you being given the quaternion rotations (or axis-angle) from the MANO hand scan registrations? or do you calculate them using that simple-ik implementation you shared above? Would this also not work for something like the FrieHAND dataset since they also include the shape/pose annotations, giving significantly more varied hand poses and views?

Hi，I got confused when saw your words. Do you mean MANO hand scan registration is also a datset to train in this project?
It would be helpful if u can give some explanation. 
Thanks!

**Comment by CalciferZh** [comment]
It's used to train the IK part.

**Comment by MengHao666** [comment]
> Regarding the supervision from the MANO scans, my understanding is that you input root-relative normalized XYZ coordinates you get an output 20x4 quaternion rotations. Are you being given the quaternion rotations (or axis-angle) from the MANO hand scan registrations? or do you calculate them using that simple-ik implementation you shared above? Would this also not work for something like the FrieHAND dataset since they also include the shape/pose annotations, giving significantly more varied hand poses and views?

Hi, guy. What do u mean by "Regarding the supervision from the MANO scans", I cannot find such corespondent description in the paper.
