### ISSUE TITLE
Did your MANO model takes in shape parameter (beta)?

### ISSUE THREAD

**Issue by Elody-07** [CalciferZh/minimal-hand#36]
Thanks for your sharing. I have several confusions.

1) The network structure in paper shows that DetNet estimation shape parameter and the mano model takes in both shape and pose parameters. But the code in app.py seems that the DetNet only outputs joint location and the mano model only needs theta to recover hand mesh. 

2) Is your IKNet pretrained using only MoCap data, then integrate it into the whole network pipeline and fintune it ? 

Thanks for your answer.

**Comment by CalciferZh** [comment]
1. Yes we only release the pose part. This is because that i) the camera intrinsic is usually unknown; ii) the shape estimation is trivial given keypoint coordinates.
2. In practice the IKNet was trained jointly with MoCap data __and__ the weak-supervision data (called 3DPosData in the paper) from scratch. But I think your approach would also work well.

**Comment by MengHao666** [comment]
sorry，what is the difference between joints and keypoints. It dose confuse me.




            
            
                
                    
                            
                                
                            
                            
                                sy1907502
                            
                    
                        
                            
                                    邮箱：sy1907502@buaa.edu.cn
                            
                        
                
            
        Signature is customized by Netease Mail Master


On 07/17/2020 20:06, Yuxiao Zhou wrote: 

Yes we only release the pose part. This is because that i) the camera intrinsic is usually unknown; ii) the shape estimation is trivial given keypoint coordinates.
In practice the IKNet was trained jointly with MoCap data and the weak-supervision data (called 3DPosData in the paper) from scratch. But I think your approach would also work well.


—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/CalciferZh/minimal-hand/issues/36#issuecomment-660071090",
"url": "https://github.com/CalciferZh/minimal-hand/issues/36#issuecomment-660071090",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by CalciferZh** [comment]
Sorry for the confusion. By keypoints mostly I mean joints.

**Comment by MengHao666** [comment]
> Sorry for the confusion. By keypoints mostly I mean joints.

Ok,thanks!
