### ISSUE TITLE
What is the rotation for finger tips for?

### ISSUE THREAD

**Issue by BenJaminB1ue** [CalciferZh/minimal-hand#55]
Hi, Zhou.
Could you tell me what is the usage for the rotation of finger tips, for I find the rotation in quaternions(wrappers.py) is 21×4 rather than 16×4, is that quaternions for finger tips redundance?
Thanks.

**Comment by CalciferZh** [comment]
We changed the MANO model a bit. We use the rotation of the child joint (instead of the parent joint as in MANO) to refer to the bone's rotation.
So, the rotation for the finger tip is actually the rotation of the last bone of the finger.
This representation makes the bones connecting the wrist and the finger-roots separately movable, while in MANO they can only move with the wrist.
