### ISSUE TITLE
About the pre-trained network model

### ISSUE THREAD

**Issue by prophett0527** [CalciferZh/minimal-hand#6]
Hello, thanks for sharing this amazing code! This is a great work!
I have a question about the pre-trained model in the Google drive.

I downloaded this pre-trained model, and ran app.py code for inference.
I noticed that the hand shape was inconsistent with some hand poses.
For example, 
1) when I tried to bend my middle finger, the hand mesh did not bend accordingly.
2) when  I rotated my hand and let the camera capture the hand side (not palm or back), the hand mesh was not generated according to the hand pose.

So, I tried to retrieve the hand pose(21-joint skeleton) by modifying this line:
`_, theta_mpii = model.process(frame)`
into
`xyz, theta_mpii = model.process(frame)`
, and displayed "xyz" in Open3D visualizer.
I found out that hand pose also had the same issues.

I have a feeling that this pre-trained model was not fully converged during training.
Could you please kindly confirm that if I am right? :)
Or is there something wrong in app.py code?
Thank you!

**Comment by CalciferZh** [comment]
Hi, I think you are using the model right. The model is not perfect and may fail on some cases, which are not covered by the training data, or due to some other reasons. We are still working on improving our model, and it would be very helpful if you could send us the failure cases via email. We'll try to figure out the possible reasons. Thank you very much for the feedback, and we'll try to push the work further.
