### ISSUE TITLE
about the shape estimation

### ISSUE THREAD

**Issue by zjhthu** [CalciferZh/minimal-hand#89]
Hi, I am wondering, once the pose and shape parameters are estimated, the absolute scale of the hand model will also be recovered. Does it mean that the network estimates an absolute-scale hand model from a single image? 
I am a new hand in this area, is the MANO model scale-independent?

**Comment by sylvanaalpert** [comment]
hi, curious about this as well. Where are the shape parameters estimated? I see the bone lengths are calculated in the ModelPipeline(), but I don't see where the beta params are. Any help is much appreciated.

**Comment by CalciferZh** [comment]
Hi.
@zjhthu The estimated beta will not be accurate because the scale is unknown. We just hope it can reflect the __relative__ hand shape.
@sylvanaalpert  The estimation of shape parameters is not released because it is not very hard to implement. Just use any solver to solve for the beta that best matches bone length. To make things clean, we only release the core part which might be not easy to reproduce.
